---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "service-center.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service-center.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.sc.service.type }}
  ports:
    - port: {{ .Values.sc.service.externalPort }}
      targetPort: {{ .Values.sc.service.internalPort }}
      {{ if eq .Values.sc.service.type "NodePort" }}
      nodePort: {{ .Values.sc.service.externalPort }}
      {{ end }}
      protocol: TCP
      name: {{ .Values.sc.service.name }}
  selector:
    app: {{ template "service-center.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "service-center.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service-center.name" . }}-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.externalPort }}
      targetPort: {{ .Values.frontend.service.internalPort }}
      {{ if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.externalPort }}
      {{ end }}
      protocol: TCP
      name: {{ .Values.frontend.service.name }}
  selector:
    app: {{ template "service-center.name" . }}-frontend
    release: {{ .Release.Name }}
