language: go

sudo: required

services:
  - docker

go:
  - 1.14

before_install:
  - go get github.com/mattn/goveralls
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
  - sudo apt-get install -y nodejs
  - npm install -g bower

before_script:
  - mkdir -p $HOME/gopath/src/github.com/apache/servicecomb-service-center
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/apache/servicecomb-service-center/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/apache/servicecomb-service-center
  - cd $HOME/gopath/src/github.com/apache/servicecomb-service-center
  - GO111MODULE=on go mod download
  - GO111MODULE=on go mod vendor
  
install: true

jobs:
  include:
    - stage: Unit Testing
      script: bash -x scripts/ut_test_in_docker.sh && $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci
    - stage: Integration Testing
      script: bash -x scripts/integration_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
