{{- if .Values.sc.ingress.enabled -}}
{{- $serviceName := include "service-center.fullname" . -}}
{{- $servicePort := .Values.sc.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "service-center.fullname" . }}
  labels:
    app: {{ template "service-center.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.sc.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.sc.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /v4/
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.sc.ingress.tls }}
  tls:
{{ toYaml .Values.sc.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
